### ISSUE TITLE
Does not handle comments (No biggie but stumbled upon this)

### ISSUE THREAD

**Issue by TommiPrami** [Xor-el/EmailValidationPascal#1]
john.smith(comment)@example.com 
or
(comment)john.smith@example.com

Both are same as  john.smith@example.com

Source : https://en.wikipedia.org/wiki/Email_address

**Comment by Xor-el** [comment]
thanks for your observations.
will review it when I have some time. 
Regards.

**Comment by Xor-el** [comment]
@mWaltari,  SMTP doesn't handle comments either in the MAIL FROM or RCPT TO commands.

There are 2 different email address specifications: SMTP and Internet Message Format.

Most people (including wikipedia) confuse the two and think they are the same, but they are not.

Comments may only appear in the From/To/Cc/etc headers of an Internet Message, but may not appear in the addresses used with SMTP.

Email Address Validation is for what? It's not for parsing emails used in a raw Internet Message document. They are for validating user-input in a text field because they will be used with SMTP.

Correct?

Then it stands to reason that an EmailValidator needs to conform to the SMTP specification and not the Internet Message Format specification.

So there's no need to handle comments (because, let's be honest, what user is going to write comments in their email address on a web form? or anywhere else for that matter?)

**Comment by TommiPrami** [comment]
Maybe there could be preprocessor method to clean all this. And spit out usable address. Justa thought. As said not a big deal. To me.

Also that method could make trivial fixes. Like trim white spaces.

Oh, also would be nice to have error code, so could give some hint to user what is wrong in the address. (And position of error if possible)

But anyways validator is very good as is...

**Comment by Xor-el** [comment]
The preprocessor part sounds cool but I don't think it will fit in the original purpose of the library,  validating email addresses as it is without modifying it. 

Regarding the specific error message request, that will require a lot of change to the current way the api is structured. 
How do we pass the error message from the validate method to the user?
An exception? 
That would add an implicit try except block and overhead to the generated code without any crucial benefit. 
An out or var parameter to the validate method? 
That would require changing the way an already existing api is used which is not always a good thing for backwards compatibility.

**Comment by TommiPrami** [comment]
1. Simple CleanEmailAddress function would do.

2. Return error code (optionally), and then method to convert it to string. If needed. Anyone would need to localize anyways. So some English reference function would do just fine.
